site_name: NewSpring Lexington Production
pages:
- Home: index.md
- NewServe:
  - First Look: newserve/firstlook.md
  - Basics:
    - Director: newserve/basics/director.md
    - Switcher: newserve/basics/switcher.md
    - Computer Graphics: newserve/basics/computergraphics.md
    - Teleprompt: newserve/basics/teleprompt.md
    - Broadcast: newserve/basics/broadcast.md
- Load In Load Out: 
  - Power: lilo/power.md
  - Audio: lilo/audio.md
  - Lighting: lilo/lighting.md
  - Screen & Projectors: lilo/screensprojectors.md
  - A-Control: lilo/acontrol.md
  - Pipe & Drape: lilo/pipedrape.md
- Training:
  - A-Control:
    - Computer Graphics: training/cg.md
    - Teleprompt: training/tp.md
    - Broadcast: training/broadcast.md
    - Director: training/director.md

theme: 'material'
extra:
  palette:
    primary: 'light green'
    accent: 'orange'

markdown_extensions:
  - admonition